# Generated by Django 2.2.5 on 2022-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleTime', models.DateTimeField(blank=True, null=True, verbose_name='점심시간')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
        migrations.CreateModel(
            name='Centerout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleEnd', models.DateTimeField(auto_now=True, verbose_name='점심시간 종료')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='result/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfPM', models.DateTimeField(blank=True, null=True, verbose_name='퇴근시간')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=128, verbose_name='이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_time', models.DateTimeField(auto_now=True, verbose_name='등록시간')),
                ('imagename', models.CharField(max_length=64, null=True, verbose_name='이미지 이름')),
                ('position', models.CharField(max_length=64, null=True, verbose_name='직책')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='부서')),
            ],
            options={
                'verbose_name': '사용자들(Meta)클래스',
                'verbose_name_plural': '사용자들(Meta)클래스',
                'db_table': 'community_myuser',
            },
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfAM', models.DateTimeField(auto_now=True, verbose_name='출근시간')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
    ]
