# Generated by Django 2.2.5 on 2022-05-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centerout',
        ),
    ]
