# Generated by Django 3.0.1 on 2020-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '사용자들(Meta)클래스', 'verbose_name_plural': '사용자들(Meta)클래스'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='abc@naver.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
