# Generated by Django 2.2.5 on 2022-05-12 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20220512_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfAM', models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 46, 10, 688480), verbose_name='출근시간')),
                ('dateTimeOfPM', models.DateTimeField(blank=True, null=True, verbose_name='퇴근시간')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
        migrations.RemoveField(
            model_name='start',
            name='dateTimeOfPM',
        ),
        migrations.AlterField(
            model_name='start',
            name='dateTimeOfAM',
            field=models.DateTimeField(auto_now=True, verbose_name='출근시간'),
        ),
    ]
