# Generated by Django 2.2.5 on 2022-05-16 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20220512_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='End',
        ),
        migrations.DeleteModel(
            name='Start',
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '근태관리_user', 'verbose_name_plural': '근태관리_user'},
        ),
        migrations.AlterField(
            model_name='test',
            name='dateTimeOfAM',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 15, 6, 6, 61653), verbose_name='출근시간'),
        ),
    ]
