# Generated by Django 2.2.5 on 2022-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Imagename',
            field=models.CharField(max_length=64, null=True, verbose_name='이미지 이름'),
        ),
    ]
