# Generated by Django 2.2.5 on 2022-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20220413_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfAM', models.DateTimeField(auto_now=True, verbose_name='출근시간')),
                ('dateTimeOfPM', models.DateTimeField(auto_now=True, verbose_name='퇴근시간')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('position', models.CharField(max_length=64, verbose_name='직책')),
                ('department', models.CharField(max_length=64, verbose_name='부서')),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Imagename',
            new_name='imagename',
        ),
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(max_length=64, null=True, verbose_name='부서'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(max_length=64, null=True, verbose_name='직책'),
        ),
    ]
