# Generated by Django 2.2.5 on 2022-05-26 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20220516_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='dateTimeOfAM',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='출근시간'),
        ),
    ]
